Repository PyThaiNLP/nlpo3, pull requests merged in 2021-11, with the labels that each got.

#46 clarify python binding load_dict behavior
  nlpo3-python/nlpo3/__init__.py
  nlpo3-python/src/lib.rs
Labels: enhancement, hacktoberfest-accepted

#45 Update Python binding README
  nlpo3-python/README.md
Labels: documentation

#47 Remove unused code + format code
  src/fixed_bytes_str/four_bytes.rs
  src/tokenizer.rs
  src/tokenizer/dict_reader_custom.rs
  src/tokenizer/newmm_custom.rs
  src/tokenizer/tcc_custom.rs
  src/tokenizer/trie_char_ver.rs
  src/tokenizer/trie_custom.rs
Labels: refactoring

#48 Update Python binding to nlpO3 1.3
  Cargo.toml
  README.md
  nlpo3-nodejs/Cargo.lock
  nlpo3-python/Cargo.lock
  nlpo3-python/Cargo.toml
  nlpo3-python/README.md
  nlpo3-python/nlpo3/__init__.py
  nlpo3-python/src/lib.rs
  src/fixed_bytes_str/four_bytes.rs
  src/lib.rs
  src/tokenizer/dict_reader_custom.rs
  src/tokenizer/newmm_custom.rs
  src/tokenizer/tcc_custom.rs
  src/tokenizer/trie_char_ver.rs
  src/tokenizer/trie_custom.rs
Labels: refactoring

#49 Update doc for Python binding
  Cargo.toml
  nlpo3-nodejs/Cargo.lock
  nlpo3-nodejs/Cargo.toml
  nlpo3-python/Cargo.toml
  nlpo3-python/pyproject.toml
  nlpo3-python/setup.cfg
Labels: documentation, refactoring

#50 Fix load_dict() output type + add unittest
  nlpo3-python/Cargo.lock
  nlpo3-python/Cargo.toml
  nlpo3-python/nlpo3/__init__.py
  nlpo3-python/pyproject.toml
  nlpo3-python/setup.cfg
  nlpo3-python/setup.py
  nlpo3-python/src/lib.rs
  nlpo3-python/tests/__init__.py
  nlpo3-python/tests/data/test_dict.txt
  nlpo3-python/tests/test_tokenize.py
Labels: bug

#52 Reformatting code
  Cargo.toml
  nlpo3-nodejs/Cargo.toml
  nlpo3-nodejs/src/lib.rs
  nlpo3-python/Cargo.toml
  nlpo3-python/pyproject.toml
  nlpo3-python/setup.cfg
  nlpo3-python/src/lib.rs
  src/NOTE_ON_STRING.md
  src/fixed_bytes_str/four_bytes.rs
  src/tokenizer.rs
  src/tokenizer/dict_reader.rs
  src/tokenizer/newmm.rs
  src/tokenizer/tcc.rs
  src/tokenizer/trie.rs
  src/tokenizer/trie_char.rs
  tests/test_tokenizer.rs
Labels: refactoring

#54 Fix slice out of range bug in CustomString::trim()
  README.md
  src/NOTE_ON_STRING.md
  src/fixed_bytes_str/four_bytes.rs
  src/tokenizer/dict_reader.rs
  src/tokenizer/trie.rs
  src/tokenizer/trie_char.rs
  tests/data/dict_with_empty_line.txt
  tests/test_tokenizer.rs
Labels: bug, refactoring

#53 Add from_word_list() for Newmm tokenizer
  README.md
  src/tokenizer/dict_reader.rs
  src/tokenizer/newmm.rs
  tests/test_tokenizer.rs
Labels: enhancement

#55 Gorlph feature/support words customization
  nlpo3-python/src/lib.rs
  src/tokenizer/newmm.rs
  src/tokenizer/trie_char.rs
  tests/test_tokenizer.rs
Labels: enhancement
